# See environment variables in file ".env"
version: '3.8'
services:
  python:
    build:
      dockerfile: docker/python/Dockerfile
      target: ${TARGET:-local} # dev or local
    shm_size: '2gb'
    environment:
    - MODELS_FOLDER=/opt/ai_development/models/
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    volumes:
    - .:/opt/ai_development
    networks:
    - app-tier
    ports:
      - 8200:8200
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1450
  app-tier:
