# See environment variables in file ".env"
version: '3.8'
services:
  ai-development:
    build:
      dockerfile: Dockerfile
      target: ${TARGET:-run} # dev or run
    image: ai-development
    container_name: ai-development
    # ipc: host
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           capabilities: [ gpu ]
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - .:/opt/ai-development
      - /mnt/sda/huggingface:/root/.cache/huggingface
    networks:
      - app-tier
    ports:
      - 8200:8200

networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1450
  app-tier:
