# See environment variables in file ".env"
version: '3.8'
services:
  ai-development:
    build:
      dockerfile: Dockerfile
      target: ${TARGET:-local} # dev or local
    container_name: ai-development
    environment:
      - LOG_FILENAME=data/logs/logfile.log
      # - MODELS_FOLDER=data/models/
      # - NVIDIA_VISIBLE_DEVICES=0
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - .:/opt/ai-development
    networks:
      - app-tier
    ports:
      - 8200:8200
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1450
  app-tier:
